"""empty message

Revision ID: 30eb62009afd
Revises: 44c2620ee25e
Create Date: 2023-09-11 17:03:01.797772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30eb62009afd'
down_revision = '44c2620ee25e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.String(length=50), nullable=True))
        batch_op.drop_column('contact_addr')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_addr', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('contact')

    # ### end Alembic commands ###
