"""empty message

Revision ID: 44c2620ee25e
Revises: 73d2d1e3bea7
Create Date: 2023-09-11 16:57:53.851184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c2620ee25e'
down_revision = '73d2d1e3bea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_no', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('contact_addr', sa.String(length=50), nullable=True))

    with op.batch_alter_table('user2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('phone_no', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('house_addr', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user2', schema=None) as batch_op:
        batch_op.drop_column('house_addr')
        batch_op.drop_column('phone_no')
        batch_op.drop_column('last_name')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('contact_addr')
        batch_op.drop_column('phone_no')

    # ### end Alembic commands ###
